### ISSUE TITLE
Problem with texturepack support

### ISSUE THREAD

**Issue by Ramcin00** [Uraxys/IdlePlus#2]
@Uraxys
About 4 days ago I decided to create the first full(currently supported) texture pack based on Minecraft textures.
Everything worked perfectly until the first 100 or so textures were introduced, the first symptoms of problems were difficulty starting the game, a moment after showing the start-screen of Unity the game closed itself, sometimes it was related to the program hanging, sometimes not. The game started after about 3/4 of starting.
After introducing about 600 textures the game stopped launching completely regardless of the number of attempts. Deleting the texturepack from the "texturepack" folder solves the problem and the game launches normally.
BepInEx console shows nothing, last note before crashing the game: 

> [Message:     Unity] CustomSteamManager init

Content of  **ErrorLog.log** is as follows:
>Setting breakpad minidump AppID = 2103530
>SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198147553602 [API loaded no]
> Fatal error. 0xC0000005
>    at Il2CppInterop.Runtime.IL2CPP.il2cpp_runtime_invoke(IntPtr, IntPtr, Void**, IntPtr ByRef)
>    at UnityEngine.ImageConversion.LoadImage(UnityEngine.Texture2D, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1<Byte>)
>    at IdlePlus.TexturePack.TexturePack.CreateAtlas(System.String)
>    at IdlePlus.TexturePack.TexturePack.Load()
>    at IdlePlus.TexturePack.TexturePackManager+<>c__DisplayClass8_0.<Load>b__1()
>    at IdlePlus.Utilities.IdleTasks+<>c__DisplayClass2_0.<Run>b__0(IdleTask)
>    at IdlePlus.Utilities.IdleTasks+IdleTask.Run()
>    at IdlePlus.Utilities.IdleTasks+IdleTask.Tick()
>    at IdlePlus.Utilities.IdleTasks.Tick()
>    at DynamicClass.Trampoline_VoidThisIdlePlus.IdlePlusBehaviourUpdate(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*)
>    at DynamicClass.Invoker_VoidThis(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*, IntPtr, IntPtr*, IntPtr*)

**Comment by Ramcin00** [comment]
So, after analyzing the code, if I'm not mistaken, all textures are loaded at the same time in CreateAtlas() method, instead of being loaded asynchronously. I'll try to modify the code as soon as I manage to finish fighting with VS, I've never worked with projects of this type in C#

**Comment by Uraxys** [comment]
Are you able to upload the pack which crashes the game?

**Comment by Ramcin00** [comment]
> Are you able to upload the pack which crashes the game?

[MC Pack.zip](https://github.com/user-attachments/files/17623428/MC.Pack.zip)

**Comment by Uraxys** [comment]
I've released [version 1.3.1](https://github.com/Uraxys/IdlePlus/releases/tag/v1.3.1), which should hopefully resolve the issue. If you could test it and let me know whether the fix works, I'd really appreciate it!

**Comment by Ramcin00** [comment]
Problem solved, good job!
